### ISSUE TITLE
glucifer memory leak

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#61]
```python
import underworld as uw
import glucifer

mesh = uw.mesh.FeMesh_Cartesian()

fig = glucifer.Figure()
fig.append( glucifer.objects.Surface(mesh,1.))

while True:
    fig.save_image("foo")
```

Memory leak occurs on both OSX (glut), and within docker (xvfb).

**Comment by RebeccaFarrington** [comment]
Can I jump on board this issue?  
Any thoughts on a fix?

2D slab model dies around 44 time steps, when fig.save_image every timestep ...

**Comment by OKaluza** [comment]
This should be fixed now, needs to be tested further but memory looks stable on my machine, see a5b961498d61b6863c1e78f483d087d6f268b9e9 and https://github.com/OKaluza/LavaVu/commit/5f37c243b45cc8169bd2a4bcd7d547bc2a3d04d3

**Comment by RebeccaFarrington** [comment]
this still crashes for me :(

using 1_07_SlabSubduction.ipynb, it crashes on the 42nd tilmestep …
(also thermal convection at 267 for a quicker test ...)

> 2016-03-29 16:43:51.627 python2.7[18855:5098441] GLUT Warning: glutInit being called a second time.
> file:glucifer_database?mode=memory&cache=shared
> Loading: file:glucifer_database?mode=memory&cache=shared
> 2016-03-29 16:43:51.692 python2.7[18855:5098441] GLUT Fatal Error: out of memory.

**Comment by OKaluza** [comment]
I'll have to test this on a Mac because it seems to be an OS X thing, slab subduction runs fine here with stable memory usage.
The posted update on the development branch should prevent all GLUT warnings caused by switching to using the renderer as a shared library, including "glutInit being called a second time". 
If you see that warning at the start then something is wrong and this will lead to other issues, ie: running out of graphics memory down the track.

**Comment by OKaluza** [comment]
Actually Bec can you please check you are using the latest updates from the development branch? An error in the recent update should have prevented any image creation using GLUT at all but yours is still working (for a while at least), which leads me to believe you didn't get the changes.

**Comment by jmansour** [comment]
owen did you see louis' pull request (lavavu)?  seems it may be related.

**Comment by OKaluza** [comment]
No I didn't see the pull request until now! That is for the same the error I just fixed that I just mentioned though.. would have prevented GLUT working at all.

**Comment by lmoresi** [comment]
Rebecca had patched the GLUT error separately if I read the email trail correctly.


On 30 March 2016 at 12:02:40 PM, OKaluza (notifications@github.com<mailto:notifications@github.com>) wrote:

No I didn't see the pull request until now! That is for the same the error I just fixed that I just mentioned though.. would have prevented GLUT working at all.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/61#issuecomment-203176989>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by OKaluza** [comment]
Yes I realise that now, I had to turn off notification emails as I was being flooded so now I don't even get notified about pull requests. If you use the mention feature (type @okaluza) I think I'll still get an email.
I am still perplexed that these GLUT warnings are happening still, will test on OS X and get back.

**Comment by RebeccaFarrington** [comment]
Hello @OKaluza !
I've just checked re this bug, it still occurs on the latest dev checkout.  
Were you able to get access to the osx machines we have at uom?  
I recall there was still problems with you accessing Ronnie.  Let me know ;)
@julesghub

**Comment by OKaluza** [comment]
This was actually a couple of issues, there were some memory leaks caused in the switch to calling the viewer as a library rather than running as an executable which have been patched.

There is another much larger leak is only showing up on OS X and caused by problems using GLUT with this library based architecture, I'm still working on that and making progress.

**Comment by OKaluza** [comment]
GLUT has been replaced on OS X with CGL for offscreen rendering and Cocoa for interactive, memory usage looks stable here (but only tested on OS X 10.8)
Should fix the last of the problems covered by this issue

**Comment by jmansour** [comment]
Offscreen seem to be working great for me (no more focus stealing!!!), but
interactive is just black.  If I run lavavu by itself, I get the little
axis widget (should there be the test pattern by default), but if I run
against a db file it's just black.

**Comment by RebeccaFarrington** [comment]
Just confirming.  Yes, I’m no longer getting memory issues with GLUT.

thanks :)

**Comment by OKaluza** [comment]
Thanks for testing @RebeccaFarrington , will close this one off then.
@jmansour I've checked in a fix for the interactive issue, if it's still happening on your machine please open another issue for that one

**Comment by RebeccaFarrington** [comment]
Thanks @OKaluza   👍
